### ISSUE TITLE
.NET framework 4.5.2 not supported

### ISSUE THREAD

**Issue by snicholmds** [lecaillon/Preconditions#1]
The project currently targets .NETStandard1.3.  That means companies like the one I work for that still use .NET framework 4.5.2 cannot use this library.  Assuming there is no code that requires standard 1.3, please lower the nuspec target so that more of us can use the library through nuget rather than copying your code directly into our projects.

The actual error I get is: 

Could not install package 'Preconditions.NET 1.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by lecaillon** [comment]
Working on it ! Indeed, nothing should limit usage of this package in a .NET Framework 4.5.2 project.

**Comment by lecaillon** [comment]
Done
