### ISSUE TITLE
Please sign or provide signed alternative

### ISSUE THREAD

**Issue by snicholmds** [lecaillon/Preconditions#2]
Only signed assemblies are allowed to run in our production environment.  Attempting to run an executable that has any dependent unsigned assemblies throws an exception like

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Foo, Version=4.3.2.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Please sign your assembly or provide a signed alternative (as YamlDotNet does).

**Comment by lecaillon** [comment]
Done, see https://www.nuget.org/packages/Preconditions.NET.StrongName/
